### ISSUE TITLE
Manjaro Settings

### ISSUE THREAD

**Issue by vinayak19th** [antony-jr/lenovo-legion5-15arh05-scripts#3]
Some of these settings don't work well on Manjaro Gnome. Would apprecitate some help with trackpad swipe gestures and Discrete mode brightness control. 

## What works:
- Gnome Pinch gestures work
- GPU Resolution & 165Hz refresh rate

## What isn't working:
- GPU Brightness control
- Swipe gestures

## Current Setup:
- Distro+Kernel : 5.13.19-2-MANJARO 
- DE : Gnome 40.5

**Comment by antony-jr** [comment]
For discrete mode brightness control you should have X.org configuration which can be found here -> https://github.com/antony-jr/lenovo-legion5-15arh05-scripts/tree/main/XOrgConfigurationNvidia (Have you tried this?)

As for swipe gestures, Let me try to live boot Manjaro Gnome and try it.

**Comment by antony-jr** [comment]
**Make sure you are not using wayland**.

**Comment by vinayak19th** [comment]
Nope I'm using the X11 back-end

**Comment by antony-jr** [comment]
> Nope I'm using the X11 back-end

Did you try this https://github.com/antony-jr/lenovo-legion5-15arh05-scripts/tree/main/XOrgConfigurationNvidia

**Comment by 123-123-nil** [comment]
Brightness control works only with NVIDIA 460.xx drivers. The [regression](https://forums.developer.nvidia.com/t/laptop-backlight-control-regression-with-465-24-02/175585) is reported and NVIDIA is working on it. Report this bug to linux-bugs@nvidia.com so that they fix it soon. I am using 495.xx drivers, it still doesn't work. My [x.config](https://pastebin.com/5FnGkFSt). Does brightness control work for you @antony-jr

**Comment by antony-jr** [comment]
> Brightness control works only with NVIDIA 460.xx drivers. The [regression](https://forums.developer.nvidia.com/t/laptop-backlight-control-regression-with-465-24-02/175585) is reported and NVIDIA is working on it. Report this bug to [linux-bugs@nvidia.com](mailto:linux-bugs@nvidia.com) so that they fix it soon. I am using 495.xx drivers, it still doesn't work. My [x.config](https://pastebin.com/5FnGkFSt). Does brightness control work for you @antony-jr

I don't have 3060, I have GTX 1650 Ti (I bought it in 2020 so). **I use hybrid graphics mode all the time so AMD iGPU is used for controlling the screen. So no brightness control issues for me for now. I use NVIDIA Prime to offload games (and heavy GPU bound software like Blender).**

@123-123-nil You should use hybrid graphics mode until the bug in nvidia driver is fixed.

**Comment by 123-123-nil** [comment]
> > Brightness control works only with NVIDIA 460.xx drivers. The [regression](https://forums.developer.nvidia.com/t/laptop-backlight-control-regression-with-465-24-02/175585) is reported and NVIDIA is working on it. Report this bug to [linux-bugs@nvidia.com](mailto:linux-bugs@nvidia.com) so that they fix it soon. I am using 495.xx drivers, it still doesn't work. My [x.config](https://pastebin.com/5FnGkFSt). Does brightness control work for you @antony-jr
> 
> I don't have 3060, I have GTX 1650 Ti (I bought it in 2020 so). **I use hybrid graphics mode all the time so AMD iGPU is used for controlling the screen. So no brightness control issues for me for now. I use NVIDIA Prime to offload games (and heavy GPU bound software like Blender).**
> 
> @123-123-nil You should use hybrid graphics mode until the bug in nvidia driver is fixed.

Yes, I am mostly using hybrid graphics only. But refresh rate is capped at 60hz in hybrid mode. Also on my machine, microphone does now work, did you face such an issue @antony-jr ?. On a bright side, brightness control works without amdgpu.backlight=0 added in kernel command line  and free sync works on hybrid mode. :)

**Comment by antony-jr** [comment]
@123-123-nil I only have issues with the brightness control. No issues with microphone, in fact it works great. I assume you have Ryzen 5000 series. So this specific amdgpu bug is with legion released in 2020 I suppose.

**Comment by vinayak19th** [comment]
Uninstall libinput-gestures and install this extention for gestures.
https://extensions.gnome.org/extension/4033/x11-gestures/

Still no good fix for brightness

**Comment by vinayak19th** [comment]
Got Brightness working in Discrete Mode using : https://wiki.archlinux.org/title/Laptop/Lenovo#Legion_series

**Comment by antony-jr** [comment]
Great. Also the fix for brightness control is in the linux 5.14.x. But this fix is only for legion 5 15ARH05 which released in 2020. So you should file a bug at https://gitlab.freedesktop.org/drm/amd something like I did which fixed my issue. https://gitlab.freedesktop.org/drm/amd/-/issues/1438
